[package]
name = "practice_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.5.0"
proc-macro2 = "1.0.93"
quote = "1.0.38"
regex = "1.11.1"
syn = { version = "2.0.96", features = ["extra-traits", "full"] }
